import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Product Inventory",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-gray-100 text-gray-800" >
        {children}

        <footer className="bg-[#FE5001] text-white text-center p-2 max-w-7xl mx-auto">© All Right Reserved</footer>
      </body>
    </html>
  );
}
